### ISSUE TITLE
Encryption Functions and CA-TA Implementation

### ISSUE THREAD

**Issue by JasonVanKerkhoven** [carleton-smart-grid/smartgrid-comms#11]
Encryption should be applied in a modular fashion to data being received by the `ta.py` as well as data being sent from any `ca.py`. A separate library should be made, similar to the `packer.py` library with 2 main functions: `encrypt()` and `decrypt`, that CA's and TA's can call.

The use of the library will have to be built into `ca.py` and `ta.py` respectively. Toggling encryption/deception should be done through the use of flags (ie on-call passing an optional `-e` or `--encrypt` flag to toggle encryption/decryption on).

**Comment by argRobertson** [comment]
Finshed, implemented on both CA and TA using the '-e' flag
