### ISSUE TITLE
Ca.py transmission error due to interface name 

### ISSUE THREAD

**Issue by NVRC** [carleton-smart-grid/smartgrid-comms#18]
When testing `ca.py` on a lowpan CA `local variable 'sock' reference before assignment` occurs on https://github.com/carleton-smart-grid/smartgrid-comms/blob/a45765c808d500416064b480ff9fa031b95a405f/mesh-comms/tcpcomms.py#L24 The  issue is prompted by using the `lowpan0` alias on development machines or vice-versa, `eth0` on lowpan devices. However, in this case the `lowpan0` alias fails on a lowpan device. https://github.com/carleton-smart-grid/smartgrid-comms/blob/a45765c808d500416064b480ff9fa031b95a405f/mesh-comms/tcpcomms.py#L23 The retransmission logic testing was preformed on a dev machine using `en0` without issue. I'll investigate further.

**Comment by JasonVanKerkhoven** [comment]
Patched in commit cda0d4d158c0cbec63c2832ff82fabc522915bee
